package pages;

public enum UsersData {
    BLOG_NAME_FIELD,
    CITY,
    CITY_FIELD,
    COUNTRY,
    COUNTRY_FIELD,
    DATE_OF_BIRTH,
    DATE_OF_BIRTH_FIELD,
    ENGLISH,
    ENGLISH_FIELD,
    FULL_DAY_CHECKBOX,
    LATIN_NAME,
    LATIN_NAME_FIELD,
    LATIN_SURNAME,
    LATIN_SURNAME_FIELD,
    LOGIN,
    NAME,
    NAME_FIELD,
    PASSWORD,
    PHONE_NUMBER,
    REMOTE_CHECKBOX,
    SURNAME,
    SURNAME_FIELD

}
